### ISSUE TITLE
Crash when fetching https://google.com/generate_204 through proxy

### ISSUE THREAD

**Issue by abliss** [zenhack/powerbox-http-proxy#2]
```
ERROR: The server threw an exception. Details:

(remote):0: failed: remote exception: remote exception: remote exception: TypeError: No field named: setShouldResetForm
    at /node_modules/capnp.js:184:15
    at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
stack: 4855b0 4514b0 449bc0 65a440 425150 41b510 4e6540 4ea250
```
Using sandstorm-269 in dev mode.

**Comment by zenhack** [comment]
I'm going to close this. Feel free to reopen if you can reproduce the problem.
